# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseAPI_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseAPI_SwiftUI
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'
end
